---
#- name: Create google vm instance
#  hosts: 
#  remote_user:
#  roles:
#    - gce-instance 
- name: Create a VM instance on Google Cloud
  hosts: localhost
  gather_facts: no
  roles:
    - gce_instance

#- name: Create a VM instance on Google Cloud
#  hosts: localhost
#  gather_facts: no
#  collections:
#    - google.cloud

